site_name: Conflux Documentation
nav:
    - Welcome to Conflux: index.md
      #    - Overview: overview.md
    - Installation: install.md
    - Getting Started: get_started.md
    - Run an Indepdent Chain: setup_independent_chain.md
    - JSON-RPC API: json-rpc.md
    - JavaScript API: javascript-api.md
    - Publish-Subscribe API: pubsub.md
    - CLI Sub-commands: cli.md
    - Design & Implementation: design.md
    - My First Transaction: send_transaction.md
    - Run a Light Node: light-nodes.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
    - fenced_code:
copyright: Copyright © 2019 Conflux. All Rights Reserved.
